version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acufi-backend
    ports:
      - "3209:3209"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - API_V1_STR=${API_V1_STR}
      - PROJECT_NAME=${PROJECT_NAME}
      - MICROSERVICE_URL=${MICROSERVICE_URL}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_EMAIL_APP_PASS=${SENDER_EMAIL_APP_PASS}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped

